In [44]:
import numpy as np

In [68]:
#### Задача1
#### Импортируйте библиотеку Numpy и дайте ей псевдоним np.
#### Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
#### Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.
#### Будем считать, что каждый столбец - это признак, а строка - наблюдение.
#### Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy.
#### Результат запишите в массив mean_a, в нем должно быть 2 элемента.


In [69]:
a = np.array([[1,2],[3,3],[1,6],[8,11],[10,7]])

In [70]:
a

array([[ 1,  2],
       [ 3,  3],
       [ 1,  6],
       [ 8, 11],
       [10,  7]])

In [71]:
mean_a = np.mean(a,axis = 0)

In [72]:
mean_a

array([4.6, 5.8])

In [73]:
#### Задача2
#### Вычислите массив a_centered, отняв от значений массива а 
#### средние значения соответствующих признаков, содержащиеся в массиве mean_a.
#### Вычисление должно производиться в одно действие.
#### Получившийся массив должен иметь размер 5x2.

In [74]:
a_centered = a-mean_a

In [75]:
a_centered

array([[-3.6, -3.8],
       [-1.6, -2.8],
       [-3.6,  0.2],
       [ 3.4,  5.2],
       [ 5.4,  1.2]])

In [76]:
#### Задание 3
#### Найдите скалярное произведение столбцов массива a_centered.
#### В результате должна получиться величина a_centered_sp. 
#### Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [77]:
a1 = a_centered[:5,0]

In [78]:
b1 = a_centered[:5,1]

In [79]:
a1,b1

(array([-3.6, -1.6, -3.6,  3.4,  5.4]), array([-3.8, -2.8,  0.2,  5.2,  1.2]))

In [80]:
a_centered_sp = a1@b1

In [81]:
a_centered_sp

41.60000000000001

In [82]:
x = a_centered_sp/(a.shape[0]-1)

In [83]:
x

10.400000000000002

In [158]:
#### Задание4
#### Число, которое мы получили в конце задания 3 является 
#### ковариацией двух признаков, содержащихся в массиве а.
#### В задании 3 мы делили сумму произведений центрированных 
#### признаков на N-1, а не на N, поэтому полученная нами величина 
#### является несмещенной оценкой ковариации.

#### В этом задании проверьте получившееся число, вычислив
#### ковариацию еще одним способом - с помощью функции np.cov.
#### В качестве аргумента m функция np.cov должна принимать транспонированный массив a.
#### В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение 
#### ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [159]:
a

array([[ 1,  2],
       [ 3,  3],
       [ 1,  6],
       [ 8, 11],
       [10,  7]])

In [160]:
a2 = a[0:,0].copy()
b2 = a[0:,1].copy()


In [161]:
c11 = np.array([list(a2),list(b2)],dtype = np.float64)

In [162]:
c11 

array([[ 1.,  3.,  1.,  8., 10.],
       [ 2.,  3.,  6., 11.,  7.]])

In [163]:
x1 = np.cov(c11)

In [164]:
x1

array([[17.3, 10.4],
       [10.4, 12.7]])

In [165]:
x1[0,1]

10.4

In [ ]:
#### Значение полученное в ходе выполнение задач 1-3 совпало со значением в задаче 4