In [44]:
import numpy as np

In [ ]:
#### Задача1
#### Импортируйте библиотеку Numpy и дайте ей псевдоним np.
#### Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
#### Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.
#### Будем считать, что каждый столбец - это признак, а строка - наблюдение.
#### Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy.
#### Результат запишите в массив mean_a, в нем должно быть 2 элемента.


In [40]:
a = np.array([[1,2],[3,3],[1,6],[8,11],[10,7]])

In [41]:
a

array([[ 1,  2],
       [ 3,  3],
       [ 1,  6],
       [ 8, 11],
       [10,  7]])

In [42]:
mean_a = np.mean(a,axis = 0)

In [43]:
mean_a

array([4.6, 5.8])

In [46]:
#### Задача2
#### Вычислите массив a_centered, отняв от значений массива а 
#### средние значения соответствующих признаков, содержащиеся в массиве mean_a.
#### Вычисление должно производиться в одно действие.
#### Получившийся массив должен иметь размер 5x2.

In [47]:
a_centered = a-mean_a

In [48]:
a_centered

array([[-3.6, -3.8],
       [-1.6, -2.8],
       [-3.6,  0.2],
       [ 3.4,  5.2],
       [ 5.4,  1.2]])